# Generated by Django 3.2 on 2021-04-26 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generic.validators
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enitity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=8)),
                ('address', models.CharField(max_length=300, null=True)),
                ('pin_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='khidmat/organization/proof/%Y/%m/%d', validators=[generic.validators.file_size_validator])),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='khidmat/organization/logos/%Y/%m/%d', validators=[generic.validators.file_size_validator])),
                ('mobile_number', models.CharField(max_length=13, unique=True, validators=[generic.validators.phone_number_validator], verbose_name='Mobile Number')),
                ('alternative_mobile_number', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[generic.validators.phone_number_validator], verbose_name='Alternative Mobile Number')),
                ('entity_type', models.PositiveSmallIntegerField(choices=[(0, 'Individual'), (1, 'Organization')], default=0)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cities_light.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization or Individual',
                'verbose_name_plural': 'Organizations or Individuals',
            },
        ),
    ]
