# Generated by Django 3.2 on 2021-04-26 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0011_auto_20210426_1925'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enitity',
            new_name='Entity',
        ),
    ]
