# Generated by Django 3.2 on 2021-04-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='extra_information',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
